### ISSUE TITLE
%FT

### ISSUE THREAD

**Issue by antoinefalisse** [MaartenAfschrift/MetabolicEnergy_Simulation#1]
Isn't there a mistake [here](https://github.com/MaartenAfschrift/MetabolicEnergy_Simulation/blob/master/MetabolicEnergy/Umberger2003/ComputeMetabolicEnergy_Umberger2003.m#L38)?

Based on the paper, I think we should divide the percentages by 100, or am I wrong?

**Comment by TDlb** [comment]
You're right, I adapted it in my code.
