### ISSUE TITLE
vMtilde in Umberger model is vM/lMopt

### ISSUE THREAD

**Issue by antoinefalisse** [MaartenAfschrift/MetabolicEnergy_Simulation#2]
@MaartenAfschrift, @TDlb 
In the Umberger model, `vMtilde = vM/lMopt` and not `vMtilde = vM/vMax`.
This is described [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Umberger2010MuscleMetabolicsProbe.cpp#L284).
In the example, this is therefore not correct to pass `vMtilde `as calculated in `FiberVelocity_Ftilde` as an argument of `ComputeMetabolicEnergy_Umberger2003`. You could replace this by:

```
vMtildeUmb = vM./auxdata.params(2,:);
[energy_total,energy_am,energy_sl,energy_mech] = ComputeMetabolicEnergy_Umberger2003(MExcitation, MActivation,...
        lMtilde,vMtildeUmb,vM,TForce,MuscleMass,TwitchRatio,10,FMltilde);
```

**Comment by TDlb** [comment]
You're right, I adapted the code.
