### ISSUE TITLE
Multiplying of total energy with muscle mass

### ISSUE THREAD

**Issue by tomvanwouwe1992** [MaartenAfschrift/MetabolicEnergy_Simulation#3]
This part of code "denormalizes" energy rates
`%% Account for muscle mass
energy_am = energy_am.*musclemass;
energy_sl = energy_sl.*musclemass;
energy_mech = energy_mech.*musclemass;
energy_total = (totalHeatRate+energy_mech).*musclemass;`

The last multiplication for the total energy seems wrong?

**Comment by antoinefalisse** [comment]
@tomvanwouwe1992, I agree.

Should be:

`energy_total = totalHeatRate.*musclemass+energy_mech;`
